# Generated by Django 3.0.8 on 2020-10-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_us_one', models.CharField(max_length=200)),
                ('about_us_two', models.CharField(max_length=200)),
                ('about_number_one', models.IntegerField()),
                ('about_number_two', models.IntegerField()),
                ('about_number_three', models.IntegerField()),
                ('about_number_four', models.IntegerField()),
                ('about_sub_title', models.CharField(max_length=10)),
                ('about_sub_para', models.CharField(max_length=200)),
                ('about_sub_para_one', models.CharField(max_length=200)),
                ('about_sub_para_two', models.CharField(max_length=200)),
                ('about_sub_para_three', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(max_length=120)),
                ('contact_message', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_title', models.CharField(max_length=120)),
                ('events_para_one', models.CharField(max_length=200)),
                ('events_para_two', models.CharField(max_length=200)),
                ('events_para_three', models.CharField(max_length=200)),
                ('events_para_four', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(max_length=100)),
                ('index_about_one', models.CharField(max_length=200)),
                ('index_about_two', models.CharField(max_length=200)),
                ('index_about_three', models.CharField(max_length=200)),
                ('index_about_four', models.CharField(max_length=200)),
                ('index_mission', models.CharField(max_length=200)),
                ('index_event_one', models.CharField(max_length=200)),
                ('index_event_two', models.CharField(max_length=200)),
                ('index_event_three', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('residential_address', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('age', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(max_length=10)),
                ('vision_para_one', models.CharField(max_length=200)),
                ('vision_para_two', models.CharField(max_length=200)),
                ('mission_para_one', models.CharField(max_length=200)),
                ('mission_para_two', models.CharField(max_length=200)),
                ('mission_para_three', models.CharField(max_length=200)),
                ('mission_para_four', models.CharField(max_length=200)),
                ('download_cp', models.FileField(upload_to='')),
                ('download_copr', models.FileField(upload_to='')),
                ('manifesto_language', models.CharField(max_length=20)),
                ('download_manifesto', models.FileField(upload_to='')),
            ],
        ),
    ]
