# Generated by Django 3.0.8 on 2020-10-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index_about_four',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_about_one',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_about_three',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_about_two',
            field=models.CharField(max_length=1000),
        ),
    ]
