# Generated by Django 3.0.8 on 2020-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201013_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_sub_para',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_sub_para_one',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_sub_para_three',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_sub_para_two',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_sub_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_one',
            field=models.CharField(max_length=1100),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_two',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_four',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_one',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_three',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_two',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vision',
            name='mission_para_four',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vision',
            name='mission_para_one',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vision',
            name='mission_para_three',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vision',
            name='mission_para_two',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vision',
            name='vision_para_one',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vision',
            name='vision_para_two',
            field=models.CharField(max_length=500),
        ),
    ]
