# Generated by Django 3.0.8 on 2020-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201013_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='events_para_four',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_one',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_three',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_para_two',
            field=models.CharField(max_length=1000),
        ),
    ]
