# Generated by Django 3.0.8 on 2020-10-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201015_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutUS',
        ),
    ]
