# Generated by Django 3.0.8 on 2020-10-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201019_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vision',
            new_name='VisionMission',
        ),
    ]
