# Generated by Django 3.0.8 on 2020-11-03 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20201104_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('residential_address', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('age', models.CharField(max_length=120)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('membership_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
